### ISSUE TITLE
Land-sea mask type

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGeo/GeoDatasets.jl#14]
Thanks for making this excellent package!

I've been playing around with the land-sea mask data a bit and have found creating a small wrapper type around it to add convenience functionality like
```julia
is_land(mask::LandSeaMask, lat::Real, lon::Real)
```
to be quite helpful. Is there a natural existing home for this within the `JuliaGeo` ecosystem, or should I create a new (very small) package? Would this package be an appropriate home for such a type, or is that kind of thing out of scope for this package?

**Comment by Alexander-Barth** [comment]
Thank you for you encouragement.
An `is_land` function would be quite useful. Are you interested to make a PR?

By the way, your work on probabilistic programming look very interesting! I need to check it out.

**Comment by willtebbutt** [comment]
Great, I'll open a PR later today. And thanks for the encouragement on the probabilistic programming stuff!

**Comment by willtebbutt** [comment]
Resolving because #15 has been merged.
