### ISSUE TITLE
Choosing a backend

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGeo/GeoDatasets.jl#16]
I've been having some issues getting `RemoteFiles`' curl backend to work to download the `gshhg` shape file (it hangs, no idea why), but `HTTP` seems to be working fine. To figure this out, I had to `]dev --local` `RemoteFiles` and change some things.

It looks like `RemoteFile`s exposes a `download` function that accepts a backend as an argument. I wonder therefore whether it would be a good idea to let users interact with that function when asking for the data in `GeoDatasets`? Perhaps a keyword argument whose default sticks with the current behaviour or something?

**Comment by Alexander-Barth** [comment]
In my tests, I was able to change the backend with:

```julia
pushfirst!(RemoteFiles.BACKENDS,RemoteFiles.Http())
```
I assume that it also works with `pushfirst!(GeoDatasets.RemoteFiles.BACKENDS,RemoteFiles.Http())`

```julia
using RemoteFiles
@RemoteFile(JULIA_BINARY, "https://status.julialang.org/download/win64",file="julia-nightly-x64.exe", updates=:daily)
download(JULIA_BINARY,verbose=true)
# [ Info: Downloading file 'julia-nightly-x64.exe' from 'https://status.julialang.org/download/win64' with cURL.
# [...]

pushfirst!(RemoteFiles.BACKENDS,RemoteFiles.Http())
@RemoteFile(JULIA_BINARY_LINUX, "https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.3-linux-x86_64.tar.gz",
           file="julia-1.5.3-linux-x86_64.tar.gz", updates=:daily)
download(JULIA_BINARY,verbose=true)
# Info: Downloading file 'julia-1.5.3-linux-x86_64.tar.gz' from 'https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.3-linux-x86_64.tar.gz' with HTTP.jl.
```

However, I am not sure if this the "recomended" way to do it. Maybe @helgee can comment on this?

**Comment by helgee** [comment]
Sorry for the belated reply. I became a father in January and my open-source activities had to go on the back burner for a while.

I have just tagged a new version of RemoteFiles.jl (0.4.0) which provides an API for overriding backends (docs)[(https://helgeeichhorn.de/RemoteFiles.jl/dev/api/#RemoteFiles.override_backends-Tuple)], e.g.

```julia
using RemoteFiles

# Only use cURL
override_backends(RemoteFiles.CURL())
download(...)

# Reset to auto-detection
reset_backends()
```

**Comment by willtebbutt** [comment]
No problem at all, and congratulations :)

> I have just tagged a new version of RemoteFiles.jl (0.4.0) which provides an API for overriding backends (docs), e.g.

This is fantastic. Thank you!

**Comment by Alexander-Barth** [comment]
Congratulations @helgee !
